dist: trusty
sudo: required
language: node_js

node_js:
  - "8.12.0"

cache:
  npm: true
  directories:
  - node_modules

  directories:
    - $HOME/.npm
    - $HOME/.sonar/cache
    - $HOME/.sonar/native-sonar-scanner

addons:
  sonarcloud:
    organization: magnobiet-github
    token:
      secure: ${SONAR_SECURE_TOKEN}
    branches:
      - master
      - develop
      - travis-ci

script:
  - sonar-scanner -X
  - npm install
  - npm run build
